// Atividades autorais da equipe; fontes de apoio conservam sua autoria.
const mission=(id,title,minutes,materials,steps,delivery,checklist,resources)=>({id,title,minutes,materials,steps,delivery,checklist,resources});
const edital='https://feiradoconhecimento.com.br/wp-content/uploads/2026/09/Edital-CFC-202601.pdf';
const obi='https://olimpiada.ic.unicamp.br/calendario/datas_importantes';
const obmep='https://www.obmep.org.br/docs/2026/anexoI.pdf';
const event=(id,title,start,end,type,area,scope,location,audience,description,source,extra={})=>({id,title,start,end,type,area,scope,location,audience,description,source,checkedAt:'2026-10-06',...extra});
export default {
 schemaVersion:1,updatedAt:'2026-10-06',
 trails:[
 {id:'programacao',title:'Programação',area:'Tecnologia e Computação',subtitle:'Da primeira referência à sua primeira página.',missions:[
 mission('prog-descobrir','Conheça quem já abriu caminhos',20,['Celular ou computador','Acesso às fontes'],['Explore o Projeto Lua, do IFCE, e o Programa Meninas Digitais.','Identifique o objetivo, o público e uma ação de cada iniciativa.','Escolha uma ação que despertou sua curiosidade e escreva por quê.'], 'Uma comparação breve das duas iniciativas, com seus links e uma possibilidade que você quer explorar.',['Consultei as duas fontes','Registrei objetivo e público','Expliquei minha escolha'],['lua','meninas-digitais']),
 mission('prog-aprender','Dê seu primeiro passo no código',35,['Computador recomendado','Editor de texto ou ambiente do material'],['Abra os materiais de programação da OBI ou do Code IoT e escolha uma introdução compatível com seu nível.','Estude uma explicação e experimente seu exemplo. Se o material exigir cadastro, você pode escolher a outra fonte.','Modifique uma entrada ou uma instrução e compare o resultado. Registre o que mudou.'],'Um exemplo executado ou descrito, a alteração feita, o resultado observado e o link do material.',['Escolhi e citei um material','Experimentei um exemplo','Descrevi a alteração e o resultado'],['obi-estude','codeiot']),
 mission('prog-criar','Crie uma página sobre uma mulher na ciência',60,['Computador','Editor de texto e navegador'],['Escolha uma mulher ligada à ciência e localize uma biografia em uma instituição de ensino, pesquisa ou museu. Anote a fonte.','Crie um arquivo index.html com título, dois parágrafos escritos por você e um link para essa fonte. Se usar imagem, confira a permissão de uso e acrescente texto alternativo.','Adicione CSS com letras legíveis e bom contraste. Abra no navegador, reduza a largura e navegue com Tab.','Revise a autoria e os fatos. Não publique dados pessoais. Você pode guardar o arquivo no aparelho.'],'O arquivo HTML produzido; no registro abaixo, descreva o conteúdo, a fonte e as verificações feitas.',['Incluí a fonte da biografia','Produzi o HTML com conteúdo próprio','Conferi leitura e navegação'],['obi-estude','codeiot']),
 mission('prog-continuar','Escolha como continuar aprendendo',20,['Sua página ou registro anterior','Catálogo Rota Delas'],['Volte à Minha rota e escolha Tecnologia e Computação e o objetivo Aprender uma habilidade ou Conhecer competições.','Abra a fonte de uma indicação e confira como estudar ou participar.','Defina uma ação pequena e um dia em que pretende fazê-la. Se houver data oficial, consulte a Agenda Delas.'],'Um próximo passo descrito com recurso, ação e momento escolhido.',['Consultei uma indicação','Conferi as condições na fonte','Defini uma ação possível'],['obi-estude','codeiot'])]},
 {id:'matematica',title:'Matemática',area:'Matemática',subtitle:'Explore, resolva e explique seu raciocínio.',missions:[
 mission('mat-explorar','Encontre uma pergunta que te interessa',20,['Celular ou computador','Papel ou editor de texto'],['Abra o Portal da OBMEP e explore os materiais disponíveis.','Escolha um assunto: proporções, geometria ou contagem, por exemplo.','Explique onde esse assunto pode aparecer no cotidiano e registre uma pergunta que deseja resolver.'],'Um assunto escolhido, uma aplicação possível, sua pergunta e a fonte.',['Explorei o portal','Escolhi um assunto','Registrei minha pergunta'],['obmep']),
 mission('mat-resolver','Resolva e conte como pensou',35,['Papel e lápis','Banco de Questões da OBMEP'],['Escolha uma questão de nível compatível com sua aprendizagem no Banco de Questões.','Tente resolver e registre as etapas, mesmo se não chegar à resposta.','Consulte a solução disponível e compare os caminhos. Descreva o que você aprendeu ou precisa revisar.'],'Identificação da questão, tentativa e comparação com a solução. Não é necessário acertar para aprender.',['Identifiquei a questão','Registrei minha tentativa','Comparei os raciocínios'],['banco-obmep']),
 mission('mat-dados','Transforme números em uma explicação',40,['Papel, planilha ou editor','Dados fictícios da atividade'],['Use estes dados fictícios de um exercício: uma biblioteca emprestou 12, 18, 15 e 25 livros em quatro semanas. Estes números não representam uma escola real.','Calcule o total, a média semanal e a diferença entre a maior e a menor quantidade.','Desenhe um gráfico de barras com eixos e título. Explique o que o gráfico mostra e o que ele não permite concluir.'],'Cálculos, gráfico e uma explicação que identifique os dados como fictícios.',['Calculei e registrei o processo','Identifiquei os dados como fictícios','Produzi e expliquei o gráfico'],['obmep']),
 mission('mat-continuar','Monte seu plano de preparação',20,['Seus registros anteriores','Catálogo e agenda'],['Escolha um tema que deseja revisar no Portal da OBMEP.','Defina duas sessões curtas de estudo e o que fará em cada uma.','Se você já foi classificada para uma etapa, consulte a agenda e confirme local e condições com sua escola. Estudar materiais não exige classificação.'],'Duas sessões planejadas com tema, material e ação.',['Escolhi um tema','Planejei duas sessões','Conferi as condições quando necessárias'],['obmep','banco-obmep'])]},
 {id:'pesquisa',title:'Investigação Científica',area:'Ciência',subtitle:'Uma investigação documental que você pode começar agora.',missions:[
 mission('pesq-pergunta','Faça uma pergunta investigável',25,['Catálogo Rota Delas','Papel ou editor'],['Explore o APICE e uma iniciativa cearense no catálogo.','Escolha uma pergunta que possa ser respondida por documentos públicos. Exemplo: que tipos de atividade são descritos em cinco iniciativas consultadas?','Escreva o que vai observar, quais fontes usará e o limite do seu recorte. Use documentos; esta atividade não propõe entrevistas, questionários ou coleta de dados pessoais.'],'Uma pergunta, objetivo, cinco fontes previstas e limites do recorte.',['Escolhi uma pergunta documental','Defini fontes e observações','Delimitei o recorte'],['apice','lua','divas-aracati']),
 mission('pesq-fontes','Organize suas evidências',40,['Cinco páginas institucionais','Papel ou planilha'],['Crie uma tabela com iniciativa, instituição, tipo de atividade, público, URL e data de consulta.','Leia as cinco fontes escolhidas e registre apenas o que estiver documentado. Use Não informado quando faltar um campo.','Revise se cada linha pode ser conferida na fonte. Descreva os critérios usados para selecionar as páginas.'],'Uma tabela rastreável com cinco fontes e os critérios de seleção.',['Registrei URLs e datas','Separei informação de interpretação','Revisei a rastreabilidade'],['apice','lua','seara']),
 mission('pesq-analisar','Compare sem exagerar as conclusões',35,['Sua tabela de fontes','Papel ou planilha'],['Agrupe as iniciativas por tipo de atividade e conte os registros em cada grupo.','Compare uma semelhança e uma diferença entre as descrições.','Responda à sua pergunta usando o recorte. Não transforme cinco páginas em um retrato de todo o Ceará ou do Brasil.'],'Uma síntese com contagem, comparação e limites sustentados pela tabela.',['Analisei o mesmo recorte','Relacionei a resposta às evidências','Registrei os limites'],['apice']),
 mission('pesq-comunicar','Apresente sua descoberta',45,['Sua tabela e síntese','Editor de texto, slides ou papel'],['Prepare uma página ou cartaz com pergunta, objetivo, método, achados e referências.','Use texto próprio e um gráfico ou tabela legível; reconheça a autoria das fontes.','Ensaiem uma explicação curta. Registre uma melhoria e um próximo passo para a investigação.'],'Um cartaz ou página e um registro breve da revisão realizada.',['Organizei pergunta, método e achados','Incluí referências','Revisei a clareza'],['apice','cfc'])]}
 ],
 events:[
 event('cfobi-inscricao-2026','CF-OBI: encerramento das inscrições','2026-09-09','2026-09-09','Inscrição','Tecnologia e Computação','Nacional','Escola participante','Competidoras inscritas pela escola','Prazo da Competição Feminina da OBI informado no calendário. As inscrições são feitas pela escola.',obi,{femaleFocus:true,opensOn:'2026-03-06'}),
 event('cfobi-prova-2026','Competição Feminina da OBI','2026-09-11','2026-09-11','Prova','Tecnologia e Computação','Nacional','Escola participante','Competidoras previamente inscritas','Prova de programação de três horas, em horário escolhido pela escola. Consulte o calendário e sua coordenação.',obi,{femaleFocus:true}),
 event('cfc-inscricao-2026','Ceará Faz Ciência: prazo de inscrição','2026-10-10','2026-10-10','Inscrição','Ciência e Pesquisa','Ceará','Envio online pelo portal oficial','Equipes elegíveis de escolas públicas do Ceará','O edital informa submissão de 11/09 a 10/10/2026, com resumo e vídeo. A consulta da agenda não realiza a inscrição.',edital,{femaleFocus:true,opensOn:'2026-09-11',certainty:'Informado no edital'}),
 event('obmep-prova-2026','OBMEP: prova da 2ª fase','2026-10-17','2026-10-17','Prova','Matemática','Nacional','Centro de aplicação definido pela OBMEP','Estudantes classificados para a 2ª fase','Início às 14h30, horário de Brasília. Confirme seu centro de aplicação com a escola. Não é uma nova inscrição.',obmep,{startsAt:'2026-10-17T17:30:00Z',timeLabel:'14h30 · horário de Brasília'}),
 event('cfc-resultado-2026','Ceará Faz Ciência: resultado previsto','2026-10-20','2026-10-20','Resultado','Ciência e Pesquisa','Ceará','Portal da Feira do Conhecimento','Equipes que enviaram projetos','Data prevista no item 9.2 do edital para divulgação dos classificados. Acompanhe eventuais comunicados oficiais.',edital,{femaleFocus:true,certainty:'Previsto no edital'}),
 event('cfc-mostra-2026','Mostra Ceará Faz Ciência','2026-11-05','2026-11-06','Evento','Ciência e Pesquisa','Ceará','Centro de Eventos do Ceará · Fortaleza','Apresentação dos projetos selecionados','Dias da mostra indicados no cabeçalho do regulamento. A apresentação depende da seleção do projeto.',edital,{femaleFocus:true}),
 event('feira-conhecimento-2026','Feira do Conhecimento 2026','2026-11-05','2026-11-07','Evento','Ciência e Pesquisa','Ceará','Centro de Eventos do Ceará · Fortaleza','Visitantes e participantes, conforme regras da feira','Evento de ciência, tecnologia e inovação. O portal oficial informa os dias e orienta o acesso dos visitantes.','https://feiradoconhecimento.com.br/'),
 event('obi-semana-2026','Semana Olímpica da OBI','2026-12-06','2026-12-12','Evento','Tecnologia e Computação','Nacional','Instituto de Computação da Unicamp · Campinas, SP','Participantes selecionados ou convidados pela OBI','Período informado no calendário da OBI. A atividade é presencial; alcance nacional não significa acesso remoto ou vaga aberta.',obi),
 event('obmep-premiados-2026','OBMEP: divulgação dos premiados','2026-12-15','2026-12-15','Resultado','Matemática','Nacional','Portal oficial da OBMEP','Participantes da edição de 2026','Data de divulgação indicada no calendário oficial. Consulte a lista no portal da organização.',obmep)
 ]
};
